# GitHub Sponsors / donation links for this repository.
# Fill these in with your actual handles/URLs.

# Example:
# github: [your-github-sponsors-handle]
# ko_fi: your_kofi
# patreon: your_patreon
# open_collective: your_open_collective
# custom: ["https://buymeacoffee.com/you", "https://paypal.me/you"]

github: sealad886
buy_me_a_coffee: sealad886
